# Generated by Django 5.2.6 on 2025-09-27 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participantes',
            old_name='email',
            new_name='correo',
        ),
    ]
