# Generated by Django 5.2.6 on 2025-10-03 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_rename_email_participantes_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='participantes',
            name='telefono',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
